language: node_js
node_js:
  - "stable"
before_install: cd API/
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c "DROP DATABASE travis;" -U postgres
  - psql -c "CREATE DATABASE travis;" -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
after_success:
  - npm run coverage