language: node_js
node_js:
  - "stable"
before_install: cd API/
cache:
  directories:
    - "node_modules"
env:
  global:
  - CODECLIMATE_REPO_TOKEN=40fde92b95fbd05ecdec8d596edd98342c027a3bb8fe75709efa7c8600dae9c0
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coverage